services:
  quartz:
    image: quartz
    ports:
      - "5230:80"
    networks:
      - wallet-network

  bot:
    image: bot
    networks:
      - wallet-network

  server:
    image: server
    ports:
      - "5221:80"
    networks:
      - wallet-network

  web:
    image: web
    ports:
      - "5162:80"
    networks:
      - wallet-network
        
networks:
  wallet-network:
    driver: bridge